pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'ap-south-1'
        REPO_URL = 'https://github.com/intfleet/auth-service'
        BRANCH = 'feature/dev-01'

        IMAGE_NAME = 'auth-service-image'
        IMAGE_TAG = "${BUILD_NUMBER}"

        K8S_NAMESPACE = 'default'
    }

    tools {
        maven 'Maven-3.9'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Source Code') {
            steps {
                git branch: "${BRANCH}", url: "${REPO_URL}"
            }
        }

        stage('Build Application') {
            steps {
                sh '''
                echo "Build Application"
                mvn clean package -DskipTests
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                echo "Build Docker Image"
                docker build -t $IMAGE_NAME:$IMAGE_TAG .
                docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                echo "Importing docker image as .tar file..."
                docker save $IMAGE_NAME:$IMAGE_TAG -o k8s/auth-service.tar
                ctr -n k8s.io images import k8s/auth-service.tar


                echo "Deploy to Kubernetes"

                export KUBECONFIG=/root/.kube/config
  
                cp k8s/deployment.yaml k8s/cp-deployment.yaml
                sed -i "s/BUILD_NUMBER/$IMAGE_TAG/g" k8s/cp-deployment.yaml

                kubectl apply -f k8s/cp-deployment.yaml -n $K8S_NAMESPACE
                kubectl apply -f k8s/service.yaml -n $K8S_NAMESPACE

                kubectl rollout status deployment/auth-service
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                sh '''
                echo "Verify Deployment"
                kubectl get pods -n $K8S_NAMESPACE
                kubectl get svc -n $K8S_NAMESPACE
                '''
            }
        }
    }

    post {
        success {
            echo 'Application deployed successfully 🚀'
        }
        failure {
            echo 'Deployment failed ❌'
        }
    }
}